'use strict';
(()=>{
const {projects,categories,categoryIcons}=window.MaynoothProjects;
const surface=document.querySelector('#map-surface'),stage=document.querySelector('#map-stage'),pins=document.querySelector('#project-pins'),panel=document.querySelector('#map-project-card'),filter=document.querySelector('#map-category'),counter=document.querySelector('#map-count');
const params=new URLSearchParams(location.search);let category=Object.hasOwn(categories,params.get('category'))?params.get('category'):'All projects';let selected=projects.find(p=>p.id===params.get('project'))||null;
if(selected)category='All projects';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
Object.keys(categories).slice(1).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;filter.append(o)});filter.value=category;
document.querySelector('#map-legend').innerHTML=Object.keys(categories).slice(1).map(c=>`<span><i style="--category:${categories[c]}"><img src="assets/${categoryIcons[c]}-icon.svg" alt=""></i>${c}</span>`).join('');
let z=1,x=0,y=0,w=0,h=0,vw=0,vh=0;
let previousView=null,restoringFocus=false;
function paint(){x=Math.min(0,Math.max(vw-w*z,x));y=Math.min(0,Math.max(vh-h*z,y));stage.style.transform=`translate(${x}px,${y}px) scale(${z})`;stage.style.setProperty('--pin-scale',1/z);document.querySelector('#map-zoom-level').value=Math.round(z*100)+'%';document.querySelector('#map-zoom-out').disabled=z<=1;document.querySelector('#map-zoom-in').disabled=z>=4}
function center(p,zoom){z=zoom||z;const mobile=vw<=800;x=vw*(mobile?.5:.4)-w*z*p.location.x/100;y=vh*(mobile?.35:.5)-h*z*p.location.y/100;paint()}
function resize(){vw=surface.clientWidth;vh=surface.clientHeight;w=Math.max(vw,vh*1.5);h=w/1.5;stage.style.width=w+'px';stage.style.height=h+'px';if(selected)center(selected,z);else{x=(vw-w*z)/2;y=(vh-h*z)/2;paint()}}
function url(){const q=new URLSearchParams();if(category!=='All projects')q.set('category',category);if(selected)q.set('project',selected.id);history.replaceState(null,'',location.pathname+(q.size?'?'+q:''))}
function show(p,move=false){if(!selected)previousView={z,x,y};selected=p;pins.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===p.id)));panel.hidden=false;panel.innerHTML=`<button class="map-card-close" aria-label="Close project preview">×</button><img class="map-card-photo" src="assets/${p.image}" alt=""><div class="map-card-content"><div class="card-labels"><span class="directory-category" style="--category:${categories[p.category]}"><img src="assets/${categoryIcons[p.category]}-icon.svg" alt="">${p.category}</span><span class="status">${p.status}</span></div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><a class="button" href="project.html?id=${p.id}">View project →</a></div>`;panel.querySelector('button').addEventListener('click',()=>close(true));counter.textContent=`${visible().length} projects · Selected: ${p.title}`;if(move)center(p,Math.max(z,1.5));url()}
function close(focus=false){const id=selected?.id;selected=null;panel.hidden=true;pins.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));counter.textContent=`Showing ${visible().length} projects`;url();if(previousView){({z,x,y}=previousView);previousView=null;paint()}if(focus&&id){restoringFocus=true;pins.querySelector(`[data-id="${id}"]`)?.focus({preventScroll:true});restoringFocus=false}}
function visible(){return projects.filter(p=>category==='All projects'||p.category===category)}
function draw(){pins.innerHTML='';for(const p of visible()){const b=document.createElement('button');b.className='map-pin';b.dataset.id=p.id;b.style.cssText=`left:${p.location.x}%;top:${p.location.y}%;--category:${categories[p.category]}`;b.setAttribute('aria-label',`${p.title}, ${p.category}, ${p.status}`);b.setAttribute('aria-pressed',String(selected?.id===p.id));b.innerHTML=`<img src="assets/${categoryIcons[p.category]}-icon.svg" alt="">`;b.addEventListener('click',()=>show(p,true));b.addEventListener('focus',()=>{if(restoringFocus)return;const sx=x+w*z*p.location.x/100,sy=y+h*z*p.location.y/100;if(sx<30||sx>vw-30||sy<30||sy>vh-30)center(p)});pins.append(b)}counter.textContent=`Showing ${visible().length} projects`}
filter.addEventListener('change',()=>{category=filter.value;close();draw();url()});
function zoom(next,cx=vw/2,cy=vh/2){next=Math.max(1,Math.min(4,next));const ratio=next/z;x=cx-(cx-x)*ratio;y=cy-(cy-y)*ratio;z=next;paint()}
document.querySelector('#map-zoom-in').addEventListener('click',()=>zoom(z*1.3));document.querySelector('#map-zoom-out').addEventListener('click',()=>zoom(z/1.3));document.querySelector('#map-reset').addEventListener('click',()=>{z=1;x=(vw-w)/2;y=(vh-h)/2;paint()});
const points=new Map();let pinch=null,drag=null;
surface.addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button>0)return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});surface.setPointerCapture(e.pointerId);surface.classList.add('is-dragging');if(points.size===1)drag={x:e.clientX,y:e.clientY};if(points.size===2){const [a,b]=[...points.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),z}}});
surface.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===2&&pinch){const [a,b]=[...points.values()],rect=surface.getBoundingClientRect();zoom(pinch.z*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance,(a.x+b.x)/2-rect.left,(a.y+b.y)/2-rect.top)}else if(drag){x+=e.clientX-drag.x;y+=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};paint()}});
function end(e){points.delete(e.pointerId);pinch=null;drag=points.size===1?[...points.values()][0]:null;if(!points.size)surface.classList.remove('is-dragging')}
surface.addEventListener('pointerup',end);surface.addEventListener('pointercancel',end);
surface.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();const r=surface.getBoundingClientRect();zoom(z*Math.exp(-e.deltaY*.005),e.clientX-r.left,e.clientY-r.top)},{passive:false});
surface.addEventListener('keydown',e=>{if(e.key==='Escape'){close(true);return}if(e.target!==surface)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')x+=80;if(e.key==='ArrowRight')x-=80;if(e.key==='ArrowUp')y+=80;if(e.key==='ArrowDown')y-=80;if(e.key==='+'||e.key==='=')zoom(z*1.3);if(e.key==='-')zoom(z/1.3);paint()}});
panel.addEventListener('keydown',e=>{if(e.key==='Escape')close(true)});
const initialProject=selected;selected=null;draw();resize();new ResizeObserver(resize).observe(surface);if(initialProject){show(initialProject);center(initialProject,2.5)}
})();
