'use strict';
(()=>{
const {projects,categories,categoryIcons}=window.MaynoothProjects;
const params=new URLSearchParams(location.search),p=projects.find(p=>p.id===params.get('id'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const backParams=new URLSearchParams(params.get('return')||'');for(const key of [...backParams.keys()])if(!['q','category','sort','view'].includes(key))backParams.delete(key);
const back='projects.html'+(backParams.size?'?'+backParams:'');
const main=document.querySelector('#main');
if(!p){main.innerHTML='<section class="container section"><h1>Project not found</h1><p>This project is not in the current directory.</p><a class="button" href="projects.html">Browse all projects</a></section>';return}
const demo=p.id==='demohouse-retrofit';
const copy={
Retrofit:{why:'Warmer homes and lower energy demand start with understanding what a retrofit involves. This project brings the choices into focus: insulation, ventilation, heating and the practical steps involved in improving an existing home.',more:'Sharing the experience helps other households ask better questions, compare their options and plan improvements that suit their home.',focus:'Home energy',cta:'Thinking about your own home?',sub:'Explore the retrofit pathway, step by step.',button:'Explore home retrofit'},
Transport:{why:'Making everyday journeys easier on foot or by bicycle can help reduce the need for short car trips. This project explores how local routes can connect people with schools, shops, green spaces and the town centre.',more:'The emphasis is on everyday usefulness: comfortable connections, clear information and opportunities for people to try a different way of travelling.',focus:'Active travel',cta:'Ready to try a different journey?',sub:'Find practical ways to walk, cycle and travel sustainably.',button:'Explore sustainable travel'},
Biodiversity:{why:'Green spaces can do more for wildlife when they are connected and cared for with nature in mind. This project explores opportunities for pollinator-friendly planting, better habitats and local participation.',more:'Small changes can create places where residents learn about nature, share growing skills and take part in looking after their surroundings.',focus:'Habitats & nature',cta:'Make room for nature.',sub:'Discover ways to take part in local climate action.',button:'Find your next action'},
Energy:{why:'Understanding where energy is used is a useful first step towards using less of it. This project explores a practical opportunity for cleaner energy and shared learning in Maynooth.',more:'The focus is on helping people ask informed questions about energy demand, suitable technology and the steps needed before making an investment.',focus:'Clean energy',cta:'Small changes, lasting habits.',sub:'Explore everyday ways to save energy at home.',button:'Explore energy actions'},
Community:{why:'Climate action becomes more approachable when people can learn and take part together. This project creates a starting point for sharing skills, meeting neighbours and trying practical ideas.',more:'Community-led activities can help useful ideas travel further, from repairing everyday items to growing food and reducing waste.',focus:'Local participation',cta:'Bring your community together.',sub:'Find an action you can share with neighbours, friends or a local group.',button:'Explore community actions'},
'Public realm':{why:'The spaces between buildings shape how a town feels and how people move through it. This project explores how greener public spaces can make everyday life more comfortable while supporting climate action.',more:'Planting, shade and spaces to pause can be considered together with access, maintenance and the needs of the people who use the town.',focus:'Greener shared spaces',cta:'Help shape a greener Maynooth.',sub:'Explore practical ways to get involved in your community.',button:'Find your next action'}
}[p.category];
const why=demo?"Homes make up 38.5% of Maynooth’s emissions. DemoHouse shows what a deep retrofit looks like from the inside: the choices, the costs, the disruption and what it feels like to live in afterwards.":copy.why;
const more=demo?'The house is a normal semi-detached home, chosen because much of the town’s housing stock looks like it. Sharing the experience helps other households understand what their own next step could be.':copy.more;
const chip=q=>`<span class="directory-category" style="--category:${categories[q.category]}"><img src="assets/${categoryIcons[q.category]}-icon.svg" alt="">${q.category}</span>`;
const related=[...projects.filter(q=>q.category===p.category&&q.id!==p.id),...projects.filter(q=>q.category!==p.category)].slice(0,3);
document.title=p.title+' | Maynooth DZ';document.querySelector('meta[name="description"]').content=p.description;
main.innerHTML=`<section class="detail-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><a href="${esc(back)}">Projects</a><span aria-hidden="true">/</span><span aria-current="page">${esc(p.title)}</span></nav><div class="detail-heading-grid"><div><p class="eyebrow">Part of the Maynooth Decarbonising Zone</p><div class="detail-labels">${chip(p)}<span class="status">${p.status}</span></div><h1>${esc(p.title)}</h1><p class="project-location">${demo?'Railpark, Maynooth':'Maynooth, County Kildare'}</p><p class="detail-lead">${demo?'A lived-in Maynooth home taken to an A-rating — opening a window into what a retrofit involves.':esc(p.description)}</p></div><a class="detail-locator" href="map.html?project=${p.id}" aria-label="Check location of ${esc(p.title)}"><span class="location-crop" style="--pin-x:${p.location.x};--pin-y:${p.location.y}"><img src="assets/map.webp" alt="Close-up of the illustrative project location"><span class="location-pin" style="--category:${categories[p.category]}"><img src="assets/${categoryIcons[p.category]}-icon.svg" alt=""></span></span><span>Check location ↗</span></a></div></div></section>
<div class="container detail-body"><p class="detail-demo-note">${demo?'Demonstration case study based on the supplied draft. Figures, map locations and supporting documents await confirmation.':'Illustrative project · Example content, photos and map locations for this demonstration.'}</p><div class="detail-layout"><article class="detail-story"><h2>Why this project</h2><p>${esc(why)}</p><p>${esc(more)}</p><figure class="detail-media"><img src="assets/${p.image}" alt="${demo?'The Maynooth demonstration house':'Illustrative local photograph for '+esc(p.title)}"><figcaption>${demo?'DemoHouse, Maynooth.':'A view of Maynooth from the project image collection.'}</figcaption></figure>${demo?'<blockquote><p>“People kept asking to see inside. Now they can.”</p><cite>Homeowner · DemoHouse <span>— quote from the supplied draft</span></cite></blockquote>':''}<section class="project-documents" aria-labelledby="documents-title"><h2 id="documents-title">Documents</h2><a class="document-download" id="download-summary" download="${p.id}-summary.html"><span class="document-type">HTML</span><span>${esc(p.title)} — project summary<small>Demonstration content · printable, accessible HTML</small></span><span aria-hidden="true">↓</span></a></section></article>
<aside class="detail-sidebar" aria-label="Project information"><section class="glance-card"><h2>At a glance</h2><dl>${demo?'<div><dt>BER before → after</dt><dd>B3 → A2</dd></div><div><dt>Energy-use reduction</dt><dd class="pending-figure">To be confirmed</dd></div><div><dt>Grants used</dt><dd class="pending-figure">To be confirmed</dd></div>':`<div><dt>Project status</dt><dd>${p.status}</dd></div><div><dt>Focus</dt><dd>${copy.focus}</dd></div><div><dt>Location</dt><dd>Maynooth</dd></div>`}</dl></section><a class="sidebar-map" href="map.html?project=${p.id}"><img src="assets/map.webp" alt="Illustrated map of Maynooth"><span>See it on the map ↗</span></a><section class="partners-card"><h2>Partners</h2>${demo?'<div class="project-partners"><span>SEAI</span><span>Maynooth SEC</span></div><p>As listed in the draft case study.</p>':'<p>Project partners to be confirmed.</p>'}</section></aside></div>
<section class="related-projects" aria-labelledby="related-title"><h2 id="related-title">Related projects</h2><div class="related-grid">${related.map(q=>`<a href="project.html?id=${q.id}" class="related-card"><img class="related-photo" src="assets/${q.image}" alt="" loading="lazy"><span>${chip(q)}<strong>${esc(q.title)}</strong></span><span class="related-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></section><section class="detail-cta"><div><h2>${copy.cta}</h2><p>${copy.sub}</p></div><a class="button" href="${p.category==='Retrofit'?'take-action.html':'index.html#action'}">${copy.button}</a></section></div>`;


const summary=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)} — summary</title><style>body{font:18px/1.65 system-ui;color:#203129;max-width:760px;margin:48px auto;padding:0 24px}h1{line-height:1.2}small{color:#526259}</style><h1>${esc(p.title)}</h1><p>${p.category} · ${p.status} · Maynooth</p><p><small>Demonstration project summary. Content and figures require confirmation.</small></p><h2>Why this project</h2><p>${esc(why)}</p><p>${esc(more)}</p><h2>Get involved</h2><p>Contact the Climate Action Office: climateaction@kildarecoco.ie</p></html>`;
const url=URL.createObjectURL(new Blob([summary],{type:'text/html'}));document.querySelector('#download-summary').href=url;

})();
